name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pyyaml
  - pip=24.3.1
  - pip:
    # changing hydra-core version to 1.3.2, as 1.3.3 does not exist
      - hydra-core==1.3.2
      - mlflow==3.4.0
      - wandb==0.22.0
